- name: install aptitude
  apt: pkg=aptitude update_cache=true
- name: Update system
  apt: upgrade=yes update_cache=true cache_valid_time=3600
- name: Install emacs editor
  apt: pkg=emacs state=present update_cache=true
- name: Create ~/.ssh directory
  file:
    path=~/.ssh
    state=directory
    owner="{{ ansible_ssh_user }}"
    group="{{ ansible_ssh_user }}"
    mode=0700
- name: Copy public key
  copy:
    src=authorized_keys
    dest=~/.ssh/authorized_keys
    owner="{{ ansible_ssh_user }}"
    group="{{ ansible_ssh_user }}"
    mode=600
